# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d1ad131e248aa4f6aca79d7ff71449f023f4517df8708b6db2ab209bc55ea78dd461da4c34a6716b898513f9ee0d7141d2bcdcd31678fd540dd42f0e2cbc372

test:
  secret_key_base: 078fb0d7a28b6d50a9b52eb590bf5c2a96b0a1d616988f8589a04b5d885073ead1df92c51a7aa55be47e2077cf4aec74175a55705deefa04f77215170a511c6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
